# Generated by Django 4.2.4 on 2023-08-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_autor_etiqueta_evento_pagina_perfil_persona_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='etiquetas',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='persona',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
